# Generated by Django 4.1.5 on 2023-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_physicalbook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalbook',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
